"""PWA Bundle Generation for Complete React Apps"""
import json
import zipfile
from pathlib import Path
from typing import Dict, List
import shutil
import os


PWA_TEMPLATE = {
    "package.json": """{
  "name": "{{name}}",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build"
  },
  "eslintConfig": {
    "extends": ["react-app"]
  },
  "browserslist": {
    "production": [">0.2%", "not dead", "not op_mini all"],
    "development": ["last 1 chrome version", "last 1 firefox version", "last 1 safari version"]
  }
}""",
    
    "public/index.html": """<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="{{theme_color}}" />
    <meta name="description" content="{{description}}" />
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
    <title>{{name}}</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>""",
    
    "public/manifest.json": """{{manifest}}""",
    
    "src/index.js": """import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// Register service worker
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/service-worker.js')
      .then(reg => console.log('SW registered:', reg))
      .catch(err => console.log('SW registration failed:', err));
  });
}""",
    
    "src/index.css": """* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  background: #050505;
  color: #fafafa;
  overflow: hidden;
}

#root {
  position: fixed;
  inset: 0;
}""",
    
    "src/App.js": """{{app_js}}""",
    
    "src/App.css": """{{app_css}}""",
    
    "src/config.js": """{{config_js}}""",
    
    "public/service-worker.js": """{{service_worker}}""",
    
    "README.md": """# {{name}}

{{description}}

## Installation

```bash
npm install
```

## Development

```bash
npm start
```

## Build

```bash
npm build
```

This PWA was generated by Project Chimera - Genesis Engine.
""",
    
    ".gitignore": """# dependencies
/node_modules

# testing
/coverage

# production
/build

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*"""
}


def generate_app_js(project: Dict, config: Dict) -> str:
    """Generate main App.js with state machine"""
    states = config.get("states", [])
    continuity = config.get("continuity", {})
    cognitive_zero = config.get("cognitiveZero", {})
    
    return f"""import React, {{ useState, useEffect, useRef }} from 'react';
import './App.css';
import config from './config';

function App() {{
  const [currentState, setCurrentState] = useState(null);
  const [backgroundIndex, setBackgroundIndex] = useState(0);
  const [audioPlaying, setAudioPlaying] = useState(false);
  const [volume, setVolume] = useState(0.7);
  const audioRef = useRef(null);
  const transitionInterval = useRef(null);

  // Initialize from config
  useEffect(() => {{
    if (config.states.length > 0) {{
      // Load saved state if continuity enabled
      if (config.continuity.remember_last_state) {{
        const saved = localStorage.getItem('atmosphere_state');
        if (saved) {{
          try {{
            const parsed = JSON.parse(saved);
            setCurrentState(parsed.stateId);
            setBackgroundIndex(parsed.backgroundIndex || 0);
            setVolume(parsed.volume || 0.7);
          }} catch (e) {{
            setCurrentState(config.states[0].id);
          }}
        }} else {{
          setCurrentState(config.states[0].id);
        }}
      }} else {{
        setCurrentState(config.states[0].id);
      }}
    }}
  }}, []);

  // Save state on changes
  useEffect(() => {{
    if (currentState && config.continuity.remember_last_state) {{
      localStorage.setItem('atmosphere_state', JSON.stringify({{
        stateId: currentState,
        backgroundIndex,
        volume,
        timestamp: Date.now()
      }}));
    }}
  }}, [currentState, backgroundIndex, volume]);

  // Background rotation
  useEffect(() => {{
    const state = config.states.find(s => s.id === currentState);
    if (state && state.visual.background_stack.length > 1) {{
      const intervalMs = (state.tempo.transition_pacing_seconds || 14) * 1000;
      
      transitionInterval.current = setInterval(() => {{
        setBackgroundIndex(prev => 
          (prev + 1) % state.visual.background_stack.length
        );
      }}, intervalMs);

      return () => clearInterval(transitionInterval.current);
    }}
  }}, [currentState]);

  const state = config.states.find(s => s.id === currentState);
  if (!state) return <div className="loading">Loading atmosphere...</div>;

  const currentBg = state.visual.background_stack[backgroundIndex];
  const nextBg = state.visual.background_stack[(backgroundIndex + 1) % state.visual.background_stack.length];

  return (
    <div className="atmosphere">
      <div 
        className="background-layer current"
        style={{{{
          backgroundImage: currentBg ? `url(${{currentBg}})` : 'none',
          opacity: 1,
          mixBlendMode: state.visual.blend_modes[0] || 'normal'
        }}}}
      />
      <div 
        className="background-layer next"
        style={{{{
          backgroundImage: nextBg ? `url(${{nextBg}})` : 'none',
          opacity: 0,
          mixBlendMode: state.visual.blend_modes[1] || 'normal'
        }}}}
      />
      
      <div className="info-overlay">
        <h1>{{name}}</h1>
        <p className="state-name">{{state.name}}</p>
        <div className="controls">
          <button onClick={{() => setAudioPlaying(!audioPlaying)}}>
            {{audioPlaying ? 'Pause' : 'Play'}}
          </button>
          <input 
            type="range" 
            min="0" 
            max="1" 
            step="0.01" 
            value={{volume}}
            onChange={{(e) => setVolume(parseFloat(e.target.value))}}
          />
        </div>
      </div>

      {{state.audio.playlist.length > 0 && (
        <audio 
          ref={{audioRef}}
          src={{state.audio.playlist[0]}}
          loop
          autoPlay={{audioPlaying}}
          volume={{volume}}
        />
      )}}
    </div>
  );
}}

export default App;
"""


def generate_app_css(project: Dict) -> str:
    """Generate App.css with atmosphere styling"""
    theme_color = project.get("pwa_manifest", {}).get("theme_color", "#050505")
    
    return f""".atmosphere {{
  position: fixed;
  inset: 0;
  overflow: hidden;
  background: {theme_color};
}}

.background-layer {{
  position: absolute;
  inset: 0;
  background-size: cover;
  background-position: center;
  transition: opacity 2s ease-in-out;
}}

.background-layer.current {{
  z-index: 1;
}}

.background-layer.next {{
  z-index: 0;
}}

.info-overlay {{
  position: fixed;
  bottom: 2rem;
  left: 2rem;
  z-index: 10;
  color: white;
  text-shadow: 0 2px 8px rgba(0,0,0,0.8);
}}

.info-overlay h1 {{
  font-size: 2rem;
  margin-bottom: 0.5rem;
  font-weight: 300;
}}

.state-name {{
  font-size: 1rem;
  opacity: 0.7;
  margin-bottom: 1rem;
}}

.controls {{
  display: flex;
  gap: 1rem;
  align-items: center;
}}

.controls button {{
  padding: 0.5rem 1rem;
  background: rgba(255,255,255,0.1);
  border: 1px solid rgba(255,255,255,0.2);
  color: white;
  border-radius: 4px;
  cursor: pointer;
  backdrop-filter: blur(10px);
}}

.controls button:hover {{
  background: rgba(255,255,255,0.2);
}}

.controls input[type="range"] {{
  width: 120px;
}}

.loading {{
  display: flex;
  align-items: center;
  justify-center;
  height: 100vh;
  font-size: 1.5rem;
  color: #888;
}}
"""


def generate_config_js(project: Dict) -> str:
    """Generate config.js with state definitions"""
    states = project.get("states", [])
    continuity = project.get("continuity", {})
    cognitive_zero = project.get("cognitive_zero", {})
    
    config = {
        "states": states,
        "continuity": continuity,
        "cognitiveZero": cognitive_zero,
        "version": "1.0.0"
    }
    
    return f"export default {json.dumps(config, indent=2)};"


def generate_service_worker(project: Dict) -> str:
    """Generate service worker"""
    name = project.get("name", "Atmosphere")
    assets = project.get("assets", [])
    
    return f"""// {name} Service Worker
const CACHE_NAME = 'atmosphere-v1';
const PRECACHE_ASSETS = [
  '/',
  '/index.html',
  '/manifest.json',
  '/static/js/main.js',
  '/static/css/main.css',
  {json.dumps(assets)}
].flat();

self.addEventListener('install', (event) => {{
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE_ASSETS))
  );
  self.skipWaiting();
}});

self.addEventListener('fetch', (event) => {{
  event.respondWith(
    caches.match(event.request)
      .then((response) => response || fetch(event.request))
      .catch(() => caches.match('/index.html'))
  );
}});

self.addEventListener('activate', (event) => {{
  event.waitUntil(
    caches.keys().then((cacheNames) => {{
      return Promise.all(
        cacheNames
          .filter((name) => name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      );
    }})
  );
}});
"""


def create_pwa_bundle(project: Dict, output_path: Path, assets_dir: Path) -> Path:
    """Create complete PWA bundle as zip"""
    project_name = project.get("name", "atmosphere-pwa").lower().replace(" ", "-")
    zip_path = output_path / f"{project_name}-bundle.zip"
    
    # Generate dynamic files
    app_js = generate_app_js(project, project)
    app_css = generate_app_css(project)
    config_js = generate_config_js(project)
    service_worker = generate_service_worker(project)
    
    manifest = project.get("pwa_manifest", {})
    manifest_json = json.dumps({
        "name": manifest.get("name", "Atmosphere"),
        "short_name": manifest.get("short_name", "Atmosphere"),
        "description": manifest.get("description", "A digital place"),
        "start_url": "/",
        "display": manifest.get("display", "standalone"),
        "orientation": manifest.get("orientation", "any"),
        "theme_color": manifest.get("theme_color", "#050505"),
        "background_color": manifest.get("background_color", "#050505"),
        "icons": [
            {"src": "/icons/icon-192.png", "sizes": "192x192", "type": "image/png"},
            {"src": "/icons/icon-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"}
        ]
    }, indent=2)
    
    # Create zip
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        # Add template files
        for file_path, template in PWA_TEMPLATE.items():
            content = template
            content = content.replace("{{name}}", project.get("name", "Atmosphere"))
            content = content.replace("{{description}}", project.get("description", "A digital place"))
            content = content.replace("{{theme_color}}", manifest.get("theme_color", "#050505"))
            content = content.replace("{{manifest}}", manifest_json)
            content = content.replace("{{app_js}}", app_js)
            content = content.replace("{{app_css}}", app_css)
            content = content.replace("{{config_js}}", config_js)
            content = content.replace("{{service_worker}}", service_worker)
            
            zipf.writestr(f"{project_name}/{file_path}", content)
        
        # Add project assets
        if assets_dir.exists():
            for asset_file in assets_dir.glob("*"):
                if asset_file.is_file() and not asset_file.name.endswith("_thumb.jpg"):
                    arcname = f"{project_name}/public/assets/{asset_file.name}"
                    zipf.write(asset_file, arcname)
        
        # Create icons directory placeholder
        zipf.writestr(f"{project_name}/public/icons/.gitkeep", "")
    
    return zip_path
